// Generated by Dart Safe Data Class Generator. * Change this header on extension settings *
// ignore_for_file: avoid_dynamic_calls, lines_longer_than_80_chars
import 'package:flutter/foundation.dart';

// Dto - Data Transfer Object são classes que representam os dados que serão
// transferidos da aplicação paro o servidor.
//
// O `LoginDto` representa os dados que server precisa para logar.
@immutable
class LoginDto {
  final String email;
  final String password;

  const LoginDto({
    required this.email,
    required this.password,
  });

  Map<String, dynamic> toMap() {
    return {
      'email': email,
      'password': password,
    };
  }
}
