// Generated by Dart Safe Data Class Generator. * Change this header on extension settings *
// ignore_for_file: avoid_dynamic_calls, lines_longer_than_80_chars
import 'package:flutter/foundation.dart';

// Dto - Data Transfer Object são classes que representam os dados que serão
// transferidos da aplicação paro o servidor.
//
// O `RegisterDto` representa os dados que server precisa para registrar.
@immutable
class RegisterDto {
  const RegisterDto({
    this.name = '',
    this.email = '',
    this.password = '',
    this.confirmPassword = '',
    this.gender = '',
    this.telephone = '',
  });

  final String name;
  final String email;
  final String password;
  final String confirmPassword;
  final String gender;
  final String telephone;

  Map<String, dynamic> toMap() {
    return {
      'name': name,
      'email': email,
      'password': password,
      'confirm_password': confirmPassword,
      'gender': gender,
      'telephone': telephone,
    };
  }

  factory RegisterDto.fromMap(Map<String, dynamic> map) {
    T isA<T>(String k) => map[k] is T
        ? map[k] as T
        : throw ArgumentError.value(map[k], k, '$T ← ${map[k].runtimeType}');
    return RegisterDto(
      name: isA<String>('name'),
      email: isA<String>('email'),
      password: isA<String>('password'),
      confirmPassword: isA<String>('confirm_password'),
      gender: isA<String>('gender'),
      telephone: isA<String>('telephone'),
    );
  }
}
