// Generated by Dart Safe Data Class Generator. * Change this header on extension settings *
// ignore_for_file: avoid_dynamic_calls, lines_longer_than_80_chars
import 'package:flutter/foundation.dart';

@immutable
class ProductModel {
  final int id;
  final String name;
  final String description;
  final double price;
  final String image;
  final int total;

  const ProductModel({
    this.id = 0,
    this.name = '',
    this.description = '',
    this.price = 0.0,
    this.image = '',
    this.total = 0,
  });

  factory ProductModel.fromJson(Map<String, dynamic> json) {
    return ProductModel(
      name: json['name'],
      description: json['description'],
      price: json['price'],
      image: json['image'],
    );
  }

  ProductModel copyWith({
    int? id,
    String? name,
    String? description,
    double? price,
    String? image,
    int? total,
  }) {
    return ProductModel(
      id: id ?? this.id,
      name: name ?? this.name,
      description: description ?? this.description,
      price: price ?? this.price,
      image: image ?? this.image,
      total: total ?? this.total,
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'id': id,
      'name': name,
      'description': description,
      'price': price,
      'image': image,
      'total': total,
    };
  }

  factory ProductModel.fromMap(Map<String, dynamic> map) {
    T isA<T>(String k) => map[k] is T
        ? map[k] as T
        : throw ArgumentError.value(map[k], k, '$T ← ${map[k].runtimeType}');
    return ProductModel(
      id: isA<int>('id'),
      name: isA<String>('name'),
      description: isA<String>('description'),
      price: isA<double>('price'),
      image: isA<String>('image'),
      total: isA<int>('total'),
    );
  }

  factory ProductModel.fromForm(Map<String, dynamic> form) {
    return ProductModel(
      id: int.parse(form['id']),
      name: form['name'],
      description: form['description'],
      price: double.parse(form['price']),
      image: form['image'],
      total: int.parse(form['total']),
    );
  }

  @override
  String toString() {
    return 'ProductModel(id: $id, name: $name, description: $description, price: $price, image: $image, total: $total)';
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;

    return other is ProductModel &&
        other.id == id &&
        other.name == name &&
        other.description == description &&
        other.price == price &&
        other.image == image &&
        other.total == total;
  }

  @override
  int get hashCode {
    return id.hashCode ^
        name.hashCode ^
        description.hashCode ^
        price.hashCode ^
        image.hashCode ^
        total.hashCode;
  }
}
